### PR TITLE
add myself as a sysadmin

### PR DESCRIPTION
**Pull request by lowpolyneko**
## Description 

Added myself as a sysadmin :3 Also, the `officers.md` page has historically had Sysadmin/Webmaster listed in the table, is that no longer a thing?

## Checklist

- [x] I've labeled the PR appropriately.
- [x] I've have built the website and verified that my changes work.
- [x] I've linked the appropriate issues and related PRs.

### CODE REVIEW

**Review by clee231 — APPROVED** [review]
Thanks for adding yourself! ❤️
Everyone on the ACM Council should generally be added to the officers.md as well. This includes SysAdmins, Webmasters, SIG/Tech Leaders, etc.

I believe the current list was sourced from one of the documents Yashi made in the council chat that was made before the semester started.

**Comment by lowpolyneko** [comment]
i can append it to the table, but i don't *actually* know who wants to be on the table lol. i'm happy to be on it, but idk if you or soham or bharat want to be on the list either. for now i'll just merge this and if people want that to be updated another pr can be done.

**Comment by lowpolyneko** [comment]
lol wait it cant get merged cus of #1031, ig i'll just keep auto-merge on. i honestly don't know enough about the eslint config to rewrite it in the flat format so i'll wait in the meantime.

**Comment by clee231** [comment]
This PR shouldn't be dependent on #1031, since that version bump hasn't been merged yet.

I think the pipeline is complaining about a linting issue. I'll look into it a bit more after work.

**Comment by clee231** [comment]
As I expected, it was just a linting error. After fixing that, the pipeline succeeded and I was able to auto-merge.

**Comment by lowpolyneko** [comment]
oh im an idiot, thanks chase :D

**Pull request merged**
